name: Build Eriador
on:
  push:
    branches:
      - refactor

jobs:
  bundle:
    name: Bundle Pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository & merge files
        uses: actions/checkout@v3

      - name: Merge files
        run: |
          cp -rf addon_eriador/. base/

      - name: Set short git commit SHA
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Replace variables
        uses: datamonsters/replace-action@v2
        with:
          files: base/pack.mcmeta
          replacements: '@commit@=${{ steps.vars.outputs.sha_short }}'

      - name: Upload pack
        uses: actions/upload-artifact@v3
        with:
          name: Eriador Pack
          path: base
          retention-days: 5

  packsquash:
    needs: bundle
    name: Optimize Pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required

      - name: Download pack
        uses: actions/download-artifact@v3
        with:
          name: Eriador Pack
          path: base

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v3
        with:
          path: base
          artifact_name: Squashed Eriador Pack
          recompress_compressed_files: true