name: Build Eriador
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bundle:
    name: Bundle Pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository & merge files
        uses: actions/checkout@v4

      - name: Merge files
        run: |
          cp -rf addon_eriador/. base/

      - name: Set short git commit SHA
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Replace variables
        uses: datamonsters/replace-action@v2
        with:
          files: base/pack.mcmeta
          replacements: '@commit@=${{ steps.vars.outputs.sha_short }}'

      - name: Upload pack
        uses: actions/upload-artifact@v4
        with:
          name: Eriador Pack
          path: base
          retention-days: 5

  packsquash:
    needs: bundle
    if: github.event_name != 'pull_request' # PRs only get preview builds
    name: Optimize Pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # A non-shallow repository clone is required

      - name: Download pack
        uses: actions/download-artifact@v4
        with:
          name: Eriador Pack
          path: base

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          artifact_name: Squashed Eriador Pack
          options: |
            pack_directory = 'base'
            recompress_compressed_files = true

  deploy:
    needs: packsquash
    if: github.event_name != 'pull_request' # PRs only get preview builds
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download pack
        uses: actions/download-artifact@v4
        with:
          name: Squashed Eriador Pack

      - name: Calculate SHA1
        id: vars
        run: |
          echo "pack_sha=$(openssl sha1 pack.zip | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Rename pack
        run: |
          mv pack.zip ${{ steps.vars.outputs.pack_sha }}.zip

      - name: Create SSH directory
        run: mkdir -p ~/.ssh
        
      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Install lftp
        run: sudo apt update && sudo apt install -y lftp
        
      - name: Upload pack using lftp
        run: |
          lftp -e "
            set ssl:verify-certificate no;
            set sftp:auto-confirm yes;
            open -u ${{ secrets.SSH_USERNAME }}, sftp://${{ secrets.SSH_HOST }}:${{ secrets.SSH_PORT }};
            put ${{ steps.vars.outputs.pack_sha }}.zip -o ${{ secrets.DEPLOY_DIRECTORY }}/${{ steps.vars.outputs.pack_sha }}.zip;
            bye
          "

      - name: Notify clients (send command)
        uses: fjogeleit/http-request-action@v1.16.4
        with:
          url: ${{ secrets.PANEL_URL }}/api/client/servers/${{ secrets.SERVER_ID }}/command
          method: POST
          bearerToken: ${{ secrets.API_KEY }}
          data: '{"command": "epicsuite packupdate eriador ${{ steps.vars.outputs.pack_sha }}"}'